### ISSUE TITLE
PDF Parser

### ISSUE THREAD

**Issue by firebolt55439** [HarkerDev/harker-lunch#2]
Maybe try something like [pdf.js](https://mozilla.github.io/pdf.js/) to allow the website to be auto-generated off the lunch PDF's? Would be easier than typing out by hand.

**Comment by aggarwalneeraj141** [comment]
patrick is working on a pdf parser right now to return some json that i'll pull from, for now its just updating weekly which isnt too bad

**Comment by 18PatZ** [comment]
Pfffft node.js

**Comment by n3a9** [comment]
Found that pdf structure was too inconsistent to write a reliable parser. Closing issue
